import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { getDictionaryResult } from "./api/hello";
import Header from "@/components/Header";
import { GetServerSideProps } from "next/types";
import { IQuery } from "../../type";
import {useState} from "react";

export default function Home({ data, error }: any) {
  console.log(data);

  const [initalQuery, setInitialQuery] = useState("dictionary");

  return (
    <>
      <Head>
        <title>Dictio | English Dictionary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.content}>
          <Header initialValue={initalQuery} />
          <h2 className="text-5xl font-bold">{data[0].word}</h2>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const isContextHasQuery = context.query.search;
  const initQuery: IQuery = { query: "" };

  let error = false;
  let data = null;

  if (isContextHasQuery == undefined || null) {
    initQuery.query = "dictionary";
  } else {
    initQuery.query = isContextHasQuery.toString();
  }

  let response = await getDictionaryResult(initQuery);
  if (response.status == 404) error = false;
  else data = response.data;

  return { props: { data, error } };
};
